### ISSUE TITLE
Warp in Shifter: ImportError: /opt/udiImage/modules/mpich/lib64/dep/libgfortran.so.5: version `GFORTRAN_10' not found

### ISSUE THREAD

**Issue by cchall** [radiasoft/containers#97]
I'm getting error trying to run Warp in Shifter with `--image=radiasoft/sirepo:prod`

Running:
```
srun --ntasks=2 --cpu-bind=cores shifter /bin/bash run_shifter.sh python -c 'import warp as wp'
```

Gives the error:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/vagrant/.pyenv/versions/py3/lib/python3.7/site-packages/warp/__init__.py", line 1, in <module>
    from .warp import *
  File "/home/vagrant/.pyenv/versions/py3/lib/python3.7/site-packages/warp/warp.py", line 109, in <module>
    from .topparallelpy import *
ImportError: /opt/udiImage/modules/mpich/lib64/dep/libgfortran.so.5: version `GFORTRAN_10' not found (required by /home/vagrant/.pyenv/versions/py3/lib/python3.7/site-packages/warp/topparallelpy.cpython-37m-x86_64-linux-gnu.so)
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/vagrant/.pyenv/versions/py3/lib/python3.7/site-packages/warp/__init__.py", line 1, in <module>
    from .warp import *
  File "/home/vagrant/.pyenv/versions/py3/lib/python3.7/site-packages/warp/warp.py", line 109, in <module>
    from .topparallelpy import *
ImportError: /opt/udiImage/modules/mpich/lib64/dep/libgfortran.so.5: version `GFORTRAN_10' not found (required by /home/vagrant/.pyenv/versions/py3/lib/python3.7/site-packages/warp/topparallelpy.cpython-37m-x86_64-linux-gnu.so)
srun: error: nid02340: tasks 0-1: Exited with exit code 1
srun: Terminating job step 41341614.7

**Comment by robnagler** [comment]
Shifter replaces our /usr/lib/mpich with theirs. I'll need to have ours in the path after theirs, but possibly as an alias to "trick" it so it finds the libgfortran.

**Comment by robnagler** [comment]
Ran some experiments, and it's going to be tricky. Some .so's may be using RPATH. Need to look at what is loaded in what order. Also may contact NERSC support.

**Comment by robnagler** [comment]
Submitted INC0167613

**Comment by robnagler** [comment]
I wasn't doing the right thing. You need a python script that looks like:

```
import mpi4py.MPI

c = mpi4py.MPI.COMM_WORLD
if c.Get_rank() == 0:
    import os
    import pykern.pkio

    l = pykern.pkio.py_path(
        os.environ['LD_LIBRARY_PATH'].split(':')[0],
    )
    l.ensure(dir=True)
    for p in pykern.pkio.sorted_glob('/lib64/libgfortran*'):
        f = l.join(p.basename)
        if not f.exists():
            f.mksymlinkto(p)
    import time
c.bcast('', root=0)
```

Note that the script has to be run before the `python -c 'import warp'` script. It can't be included in the script. I called it `link-libgfortran.py`, and it is called like this:

```sh
#!/bin/bash
#SBATCH --image=radiasoft/sirepo:prod
#SBATCH --constraint=haswell
#SBATCH --qos=debug
#SBATCH --tasks-per-node=32
#SBATCH --ntasks=2
#SBATCH --time=0:5
cat > bash.stdin <<'EOF'
ulimit -c 0
unset PYTHONPATH
unset PYTHONSTARTUP
export PYENV_ROOT=/home/vagrant/.pyenv
export HOME=/home/vagrant
source /home/vagrant/.bashrc >& /dev/null
eval export HOME=~$USER
export LD_LIBRARY_PATH=$PWD/libgfortran:$LD_LIBRARY_PATH
python link-libgfortran.py
python -c 'import warp'
EOF
exec srun shifter /bin/bash bash.stdin
```


Now https://github.com/radiasoft/container-beamsim/issues/5 is even more important.

**Comment by cchall** [comment]
This shouldn't be an issue anymore
